[package]
name = "ic-vetkeys"
version = "0.1.0"
description = "A set of tools designed to help canister developers integrate vetKeys into their Internet Computer (ICP) applications"
keywords = [
  "vetkeys",
  "vetkd",
  "encryption",
  "privacy",
  "signature",
  "bls",
  "key-derivation",
  "ibe",
]
license = "Apache-2.0"

[dependencies]
base = "0.14.6"

[dev-dependencies]
test = "2.1.1"
