[package]
name = "ic-vetkeys"
version = "0.3.0"
repository = "https://github.com/dfinity/vetkeys/backend/mo/ic_vetkeys"
description = "A set of tools designed to help canister developers integrate vetKeys into their Internet Computer (ICP) applications"
keywords = [
  "vetkeys",
  "vetkd",
  "encryption",
  "privacy",
  "signature",
  "bls",
  "key-derivation",
  "ibe"
]
license = "Apache-2.0"

[dependencies]
base = "0.14.9"

[dev-dependencies]
test = "2.1.1"
