[workspace]
members = ["backend"]
resolver = "2"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'

[patch.crates-io]
identicon-rs = { git = 'https://github.com/randombit/identicon-rs.git', branch = 'jack/min-image-features' }
