/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./ic_vetkeys_encrypted_maps_canister.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_4 = {
    __kind__: "Ok";
    Ok: AccessRights | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_2 = {
    __kind__: "Ok";
    Ok: ByteBuf;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result = {
    __kind__: "Ok";
    Ok: ByteBuf | null;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_3 = {
    __kind__: "Ok";
    Ok: Array<[Principal, AccessRights]>;
} | {
    __kind__: "Err";
    Err: string;
};
export interface EncryptedMapData {
    access_control: Array<[Principal, AccessRights]>;
    keyvals: Array<[ByteBuf, ByteBuf]>;
    map_name: ByteBuf;
    map_owner: Principal;
}
export type Result_5 = {
    __kind__: "Ok";
    Ok: Array<ByteBuf>;
} | {
    __kind__: "Err";
    Err: string;
};
export interface ByteBuf {
    inner: Uint8Array;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: Array<[ByteBuf, ByteBuf]>;
} | {
    __kind__: "Err";
    Err: string;
};
export enum AccessRights {
    Read = "Read",
    ReadWrite = "ReadWrite",
    ReadWriteManage = "ReadWriteManage"
}
export interface ic_vetkeys_encrypted_maps_canisterInterface {
    get_accessible_shared_map_names(): Promise<Array<[Principal, ByteBuf]>>;
    get_all_accessible_encrypted_maps(): Promise<Array<EncryptedMapData>>;
    get_all_accessible_encrypted_values(): Promise<Array<[[Principal, ByteBuf], Array<[ByteBuf, ByteBuf]>]>>;
    get_encrypted_value(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf): Promise<Result>;
    get_encrypted_values_for_map(arg0: Principal, arg1: ByteBuf): Promise<Result_1>;
    get_encrypted_vetkey(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf): Promise<Result_2>;
    get_owned_non_empty_map_names(): Promise<Array<ByteBuf>>;
    get_shared_user_access_for_map(arg0: Principal, arg1: ByteBuf): Promise<Result_3>;
    get_user_rights(arg0: Principal, arg1: ByteBuf, arg2: Principal): Promise<Result_4>;
    get_vetkey_verification_key(): Promise<ByteBuf>;
    insert_encrypted_value(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf, arg3: ByteBuf): Promise<Result>;
    remove_encrypted_value(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf): Promise<Result>;
    remove_map_values(arg0: Principal, arg1: ByteBuf): Promise<Result_5>;
    remove_user(arg0: Principal, arg1: ByteBuf, arg2: Principal): Promise<Result_4>;
    set_user_rights(arg0: Principal, arg1: ByteBuf, arg2: Principal, arg3: AccessRights): Promise<Result_4>;
}
import type { AccessRights as _AccessRights, ByteBuf as _ByteBuf, EncryptedMapData as _EncryptedMapData, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5 } from "./ic_vetkeys_encrypted_maps_canister.did";
export class Ic_vetkeys_encrypted_maps_canister implements ic_vetkeys_encrypted_maps_canisterInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_accessible_shared_map_names(): Promise<Array<[Principal, ByteBuf]>> {
        const result = await this.actor.get_accessible_shared_map_names();
        return result;
    }
    async get_all_accessible_encrypted_maps(): Promise<Array<EncryptedMapData>> {
        const result = await this.actor.get_all_accessible_encrypted_maps();
        return from_candid_vec_n1(result);
    }
    async get_all_accessible_encrypted_values(): Promise<Array<[[Principal, ByteBuf], Array<[ByteBuf, ByteBuf]>]>> {
        const result = await this.actor.get_all_accessible_encrypted_values();
        return result;
    }
    async get_encrypted_value(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf): Promise<Result> {
        const result = await this.actor.get_encrypted_value(arg0, arg1, arg2);
        return from_candid_Result_n8(result);
    }
    async get_encrypted_values_for_map(arg0: Principal, arg1: ByteBuf): Promise<Result_1> {
        const result = await this.actor.get_encrypted_values_for_map(arg0, arg1);
        return from_candid_Result_1_n11(result);
    }
    async get_encrypted_vetkey(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf): Promise<Result_2> {
        const result = await this.actor.get_encrypted_vetkey(arg0, arg1, arg2);
        return from_candid_Result_2_n13(result);
    }
    async get_owned_non_empty_map_names(): Promise<Array<ByteBuf>> {
        const result = await this.actor.get_owned_non_empty_map_names();
        return result;
    }
    async get_shared_user_access_for_map(arg0: Principal, arg1: ByteBuf): Promise<Result_3> {
        const result = await this.actor.get_shared_user_access_for_map(arg0, arg1);
        return from_candid_Result_3_n15(result);
    }
    async get_user_rights(arg0: Principal, arg1: ByteBuf, arg2: Principal): Promise<Result_4> {
        const result = await this.actor.get_user_rights(arg0, arg1, arg2);
        return from_candid_Result_4_n17(result);
    }
    async get_vetkey_verification_key(): Promise<ByteBuf> {
        const result = await this.actor.get_vetkey_verification_key();
        return result;
    }
    async insert_encrypted_value(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf, arg3: ByteBuf): Promise<Result> {
        const result = await this.actor.insert_encrypted_value(arg0, arg1, arg2, arg3);
        return from_candid_Result_n8(result);
    }
    async remove_encrypted_value(arg0: Principal, arg1: ByteBuf, arg2: ByteBuf): Promise<Result> {
        const result = await this.actor.remove_encrypted_value(arg0, arg1, arg2);
        return from_candid_Result_n8(result);
    }
    async remove_map_values(arg0: Principal, arg1: ByteBuf): Promise<Result_5> {
        const result = await this.actor.remove_map_values(arg0, arg1);
        return from_candid_Result_5_n20(result);
    }
    async remove_user(arg0: Principal, arg1: ByteBuf, arg2: Principal): Promise<Result_4> {
        const result = await this.actor.remove_user(arg0, arg1, arg2);
        return from_candid_Result_4_n17(result);
    }
    async set_user_rights(arg0: Principal, arg1: ByteBuf, arg2: Principal, arg3: AccessRights): Promise<Result_4> {
        const result = await this.actor.set_user_rights(arg0, arg1, arg2, to_candid_AccessRights_n22(arg3));
        return from_candid_Result_4_n17(result);
    }
}
function from_candid_AccessRights_n6(value: _AccessRights): AccessRights {
    return from_candid_variant_n7(value);
}
function from_candid_EncryptedMapData_n2(value: _EncryptedMapData): EncryptedMapData {
    return from_candid_record_n3(value);
}
function from_candid_Result_1_n11(value: _Result_1): Result_1 {
    return from_candid_variant_n12(value);
}
function from_candid_Result_2_n13(value: _Result_2): Result_2 {
    return from_candid_variant_n14(value);
}
function from_candid_Result_3_n15(value: _Result_3): Result_3 {
    return from_candid_variant_n16(value);
}
function from_candid_Result_4_n17(value: _Result_4): Result_4 {
    return from_candid_variant_n18(value);
}
function from_candid_Result_5_n20(value: _Result_5): Result_5 {
    return from_candid_variant_n21(value);
}
function from_candid_Result_n8(value: _Result): Result {
    return from_candid_variant_n9(value);
}
function from_candid_opt_n10(value: [] | [_ByteBuf]): ByteBuf | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(value: [] | [_AccessRights]): AccessRights | null {
    return value.length === 0 ? null : from_candid_AccessRights_n6(value[0]);
}
function from_candid_record_n3(value: {
    access_control: Array<[Principal, _AccessRights]>;
    keyvals: Array<[_ByteBuf, _ByteBuf]>;
    map_name: _ByteBuf;
    map_owner: Principal;
}): {
    access_control: Array<[Principal, AccessRights]>;
    keyvals: Array<[ByteBuf, ByteBuf]>;
    map_name: ByteBuf;
    map_owner: Principal;
} {
    return {
        access_control: from_candid_vec_n4(value.access_control),
        keyvals: value.keyvals,
        map_name: value.map_name,
        map_owner: value.map_owner
    };
}
function from_candid_tuple_n5(value: [Principal, _AccessRights]): [Principal, AccessRights] {
    return [
        value[0],
        from_candid_AccessRights_n6(value[1])
    ];
}
function from_candid_variant_n12(value: {
    Ok: Array<[_ByteBuf, _ByteBuf]>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<[ByteBuf, ByteBuf]>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n14(value: {
    Ok: _ByteBuf;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ByteBuf;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n16(value: {
    Ok: Array<[Principal, _AccessRights]>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<[Principal, AccessRights]>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n4(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n18(value: {
    Ok: [] | [_AccessRights];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: AccessRights | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n19(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n21(value: {
    Ok: Array<_ByteBuf>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ByteBuf>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n7(value: {
    Read: null;
} | {
    ReadWrite: null;
} | {
    ReadWriteManage: null;
}): AccessRights {
    return "Read" in value ? AccessRights.Read : "ReadWrite" in value ? AccessRights.ReadWrite : "ReadWriteManage" in value ? AccessRights.ReadWriteManage : value;
}
function from_candid_variant_n9(value: {
    Ok: [] | [_ByteBuf];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ByteBuf | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n10(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n1(value: Array<_EncryptedMapData>): Array<EncryptedMapData> {
    return value.map((x)=>from_candid_EncryptedMapData_n2(x));
}
function from_candid_vec_n4(value: Array<[Principal, _AccessRights]>): Array<[Principal, AccessRights]> {
    return value.map((x)=>from_candid_tuple_n5(x));
}
function to_candid_AccessRights_n22(value: AccessRights): _AccessRights {
    return to_candid_variant_n23(value);
}
function to_candid_variant_n23(value: AccessRights): {
    Read: null;
} | {
    ReadWrite: null;
} | {
    ReadWriteManage: null;
} {
    return value == AccessRights.Read ? {
        Read: null
    } : value == AccessRights.ReadWrite ? {
        ReadWrite: null
    } : value == AccessRights.ReadWriteManage ? {
        ReadWriteManage: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Ic_vetkeys_encrypted_maps_canister {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Ic_vetkeys_encrypted_maps_canister(actor);
}
