// This canister is a thin reference wrapper around the `ic-vetkeys`
// EncryptedMaps library. The entire canister interface is generated by the
// library macro, which guarantees the exposed Candid matches what the
// `@icp-sdk/vetkeys` frontend expects.
ic_vetkeys::export_encrypted_maps_canister!("encrypted_maps_dapp");

ic_cdk::export_candid!();
