[package]
name = "ic-vetkeys-manager-canister"
version = "0.1.0"
repository = "https://github.com/dfinity/vetkeys"
keywords = [
  "vetkeys,vetkd,encryption,privacy,signature,BLS,key ",
  "derivation,IBE"
]
license = "Apache-2.0"

[dependencies]
base = "0.14.6"
