name: Backend Motoko Format Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    paths:
      - backend/mo/**
      - .github/workflows/provision-linux.sh
      - .github/workflows/backend-motoko-format-check.yml

jobs:
  backend-motoko-format-check-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Run MOPS Format Check Linux
        run: |
          cd backend/mo/ic_vetkeys
          echo "Checking directory: $(pwd)" && mops format --check
          cd ../canisters
          for d in $(ls); do cd $d && echo "Checking directory: $(pwd)" && mops format --check; cd ..; done
