name: Backend CI Rust
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - backend/rs/benchmarks/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/provision-linux.sh
      - .github/workflows/provision-darwin.sh
      - .github/workflows/backend-rust-canbench.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo-test-backend-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Run Tests Linux
        run: |
          set -eExuo pipefail
          export CARGO_TERM_COLOR=always # ensure output has colors
          cd backend/rs/benchmarks/ibe
          cargo install canbench
          canbench
