# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: examples-password-manager
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/password_manager/**
      - backend/**
      - Cargo.toml
      - Cargo.lock
      - frontend/ic_vetkeys/**
      - package.json
      - package-lock.json
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/examples-password-manager.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-examples-password-manager-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Password Manager Darwin
        run: |
          set -eExuo pipefail
          npm i
          pushd examples/password_manager
          ln -sf dfx_configs/dfx_rust.json dfx.json
          ./deploy_locally.sh
          cd frontend
          npm run lint
  rust-examples-password-manager-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager Linux
        run: |
          set -eExuo pipefail
          npm i
          pushd examples/password_manager
          ln -sf dfx_configs/dfx_rust.json dfx.json
          ./deploy_locally.sh
          cd frontend
          npm run lint
  motoko-examples-password-manager-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Password Manager Darwin
        run: |
          set -eExuo pipefail
          npm i
          pushd examples/password_manager
          ./deploy_locally.sh
          cd frontend
          npm run lint
  motoko-examples-password-manager-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager Linux
        run: |
          set -eExuo pipefail
          npm i
          pushd examples/password_manager
          ./deploy_locally.sh
          cd frontend
          npm run lint