# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: examples-password-manager-with-metadata
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/password_manager_with_metadata/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/examples-password-manager-with-metadata.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  examples-password-manager-with-metadata-rust-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Password Manager With Metadata Darwin
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          cd examples/password_manager_with_metadata/rust
          dfx start --background && dfx deploy
          cd frontend
          npm run lint
  examples-password-manager-with-metadata-rust-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager With Metadata Linux
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          cd examples/password_manager_with_metadata/rust
          dfx start --background && dfx deploy
          cd frontend
          npm run lint
  examples-password-manager-with-metadata-motoko-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Password Manager With Metadata Darwin
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          cd examples/password_manager_with_metadata/motoko
          dfx start --background && dfx deploy
          cd frontend
          npm run lint
  examples-password-manager-with-metadata-motoko-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager With Metadata Linux
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          cd examples/password_manager_with_metadata/motoko
          dfx start --background && dfx deploy
          cd frontend
          npm run lint