# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: examples-password-manager
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/password_manager/**
      - backend/**
      - Cargo.toml
      - Cargo.lock
      - frontend/ic_vetkeys/**
      - package.json
      - package-lock.json
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/examples-password-manager.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  examples-password-manager-rust-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Password Manager Darwin
        run: |
          set -eExuo pipefail
          cd examples/password_manager/rust
          dfx start --background && dfx deploy
          cd frontend
          npm run lint
  examples-password-manager-rust-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager Linux
        run: |
          set -eExuo pipefail
          cd examples/password_manager/rust
          dfx start --background && dfx deploy
          cd frontend
          npm run lint
  examples-password-manager-motoko-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Password Manager Darwin
        run: |
          set -eExuo pipefail
          cd examples/password_manager/motoko
          dfx start --background && dfx deploy
          cd frontend
          npm run lint
  examples-password-manager-motoko-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager Linux
        run: |
          set -eExuo pipefail
          cd examples/password_manager/motoko
          dfx start --background && dfx deploy
          cd frontend
          npm run lint