name: examples-basic-ibe
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/basic_ibe/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/examples-basic-ibe.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  examples-basic-ibe-rust-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Basic IBE Rust Darwin
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_ibe/rust
          icp network start -d && icp deploy
          cd frontend
          npm run lint
  examples-basic-ibe-rust-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Basic IBE Rust Linux
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_ibe/rust
          icp network start -d && icp deploy
          cd frontend
          npm run lint
  examples-basic-ibe-motoko-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Basic IBE Motoko Darwin
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_ibe/motoko
          icp network start -d && icp deploy
          cd frontend
          npm run lint
  examples-basic-ibe-motoko-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Basic IBE Motoko Linux
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_ibe/motoko
          icp network start -d && icp deploy
          cd frontend
          npm run lint
