name: examples-basic-bls-signing

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/basic_bls_signing/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/examples-basic-bls-signing.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  examples-basic-bls-signing-rust-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Basic BLS Signing Rust Darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_bls_signing/rust
          icp network start -d && icp deploy
          cd frontend
          npm run lint
  examples-basic-bls-signing-rust-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Basic BLS Signing Rust Linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_bls_signing/rust
          icp network start -d && icp deploy
          cd frontend
          npm run lint
  examples-basic-bls-signing-motoko-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Basic BLS Signing Motoko Darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_bls_signing/motoko
          icp network start -d && icp deploy
          cd frontend
          npm run lint
  examples-basic-bls-signing-motoko-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Basic BLS Signing Motoko Linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eExuo pipefail
          cargo install candid-extractor
          pushd examples/basic_bls_signing/motoko
          icp network start -d && icp deploy
          cd frontend
          npm run lint
